// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bronzetti.christian._5h.PrimoEF.Models;

namespace bronzetti.christian._5h.PrimoEF.Migrations
{
    [DbContext(typeof(DbPersone))]
    [Migration("20211015074038_primaVersione")]
    partial class primaVersione
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("bronzetti.christian._5h.PrimoEF.Models.Persona", b =>
                {
                    b.Property<int>("PersonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaID");

                    b.ToTable("Persone");
                });
#pragma warning restore 612, 618
        }
    }
}
